/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature Flags */
        get: operations["feature_flags_api_v1_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offers */
        get: operations["offers_api_v1_offers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankMetadata */
        BankMetadata: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** DateStripItem */
        DateStripItem: {
            /** Date */
            date: string;
            /** Display Text */
            display_text: string;
        };
        /** FeatureFlagsResponse */
        FeatureFlagsResponse: {
            /** Analyticsenabled */
            analyticsEnabled: boolean;
            /** Bookingamountcomparisonenabled */
            bookingAmountComparisonEnabled: boolean;
            /** Couponcodeenabled */
            couponCodeEnabled: boolean;
            /** Phase2Userfeaturesenabled */
            phase2UserFeaturesEnabled: boolean;
            /** Publicalloffersenabled */
            publicAllOffersEnabled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OfferMetadata */
        OfferMetadata: {
            /** Airports */
            airports?: {
                [key: string]: unknown;
            }[];
            /** Banks */
            banks: components["schemas"]["BankMetadata"][];
            /** Booking Channels */
            booking_channels: ("WEB" | "APP" | "WEB_AND_APP")[];
            /** Categories */
            categories: "FLIGHT_DOMESTIC"[];
            /** Data Version */
            data_version: string;
            /** Payment Methods */
            payment_methods: ("CREDIT" | "DEBIT" | "NO_CARD")[];
            /** Platforms */
            platforms: components["schemas"]["PlatformMetadata"][];
        };
        /** OffersResponse */
        OffersResponse: {
            /** Data Version */
            data_version: string;
            /** Facets */
            facets?: null;
            /** Offers */
            offers: components["schemas"]["PublicOffer"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Pagination */
        Pagination: {
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PlatformMetadata */
        PlatformMetadata: {
            /**
             * Id
             * @enum {string}
             */
            id: "MAKEMYTRIP" | "CLEARTRIP";
            /** Name */
            name: string;
        };
        /** PublicOffer */
        PublicOffer: {
            /** Bank Id */
            bank_id: string | null;
            /** Bank Name */
            bank_name: string | null;
            /**
             * Booking Channel
             * @enum {string}
             */
            booking_channel: "WEB" | "APP" | "WEB_AND_APP";
            /** Card Name */
            card_name: string | null;
            /**
             * Category
             * @constant
             */
            category: "FLIGHT_DOMESTIC";
            /** Coupon Code */
            coupon_code: string | null;
            /**
             * Discount Type
             * @enum {string}
             */
            discount_type: "PERCENT" | "FLAT";
            /** Discount Value */
            discount_value: number | null;
            /** Eligibility Notes */
            eligibility_notes: string[];
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Login Required */
            login_required: boolean;
            /** Max Discount */
            max_discount: number | null;
            /** Min Transaction */
            min_transaction: number | null;
            /** New User Only */
            new_user_only: boolean;
            /** Offer Id */
            offer_id: string;
            /** Offer Title */
            offer_title: string;
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "CREDIT" | "DEBIT" | "NO_CARD";
            /**
             * Platform Id
             * @enum {string}
             */
            platform_id: "MAKEMYTRIP" | "CLEARTRIP";
            /** Platform Name */
            platform_name: string;
            /** Terms Url */
            terms_url: string | null;
            /** Usage Limit */
            usage_limit: string | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
        };
        /** SearchOffer */
        SearchOffer: {
            /** Bank Id */
            bank_id: string | null;
            /** Bank Name */
            bank_name: string | null;
            /**
             * Booking Channel
             * @enum {string}
             */
            booking_channel: "WEB" | "APP" | "WEB_AND_APP";
            /** Booking Url */
            booking_url: string | null;
            /** Card Name */
            card_name: string | null;
            /**
             * Category
             * @constant
             */
            category: "FLIGHT_DOMESTIC";
            /** Coupon Code */
            coupon_code: string | null;
            /**
             * Discount Type
             * @enum {string}
             */
            discount_type: "PERCENT" | "FLAT";
            /** Discount Value */
            discount_value: number | null;
            /** Display Kind */
            display_kind: string;
            /** Display Rank */
            display_rank: number;
            /** Eligibility Notes */
            eligibility_notes: string[];
            /** Estimated Final Amount */
            estimated_final_amount: number | null;
            /** Estimated Savings */
            estimated_savings: number | null;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Max Discount */
            max_discount: number | null;
            /** Min Transaction */
            min_transaction: number | null;
            /** New User Only */
            new_user_only: boolean;
            /** Offer Id */
            offer_id: string;
            /** Offer Title */
            offer_title: string;
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "CREDIT" | "DEBIT" | "NO_CARD";
            /**
             * Platform Id
             * @enum {string}
             */
            platform_id: "MAKEMYTRIP" | "CLEARTRIP";
            /** Platform Name */
            platform_name: string;
            /** Savings Delta */
            savings_delta: number | null;
            /** Savings Label */
            savings_label: string;
            /** Terms Url */
            terms_url: string | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Banks */
            banks?: string[];
            /** Booking Amount */
            booking_amount?: number | string | null;
            /**
             * Category
             * @default FLIGHT_DOMESTIC
             * @constant
             */
            category: "FLIGHT_DOMESTIC";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** From */
            from: string;
            /** Platforms */
            platforms?: ("MAKEMYTRIP" | "CLEARTRIP")[];
            /** To */
            to: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Data Version */
            data_version: string;
            /** Date Strip */
            date_strip?: components["schemas"]["DateStripItem"][];
            /** Offers */
            offers: components["schemas"]["SearchOffer"][];
            summary: components["schemas"]["SearchSummary"];
        };
        /** SearchSummary */
        SearchSummary: {
            /** Booking Amount */
            booking_amount: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    feature_flags_api_v1_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagsResponse"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferMetadata"];
                };
            };
        };
    };
    offers_api_v1_offers_get: {
        parameters: {
            query?: {
                bank?: string[];
                platform?: string[];
                payment_method?: ("CREDIT" | "DEBIT" | "NO_CARD") | null;
                booking_channel?: ("WEB" | "APP" | "WEB_AND_APP") | null;
                category?: "FLIGHT_DOMESTIC" | null;
                active_on?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OffersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
