/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature Flags */
        get: operations["feature_flags_api_v1_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offers */
        get: operations["offers_api_v1_offers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AirportMetadata */
        AirportMetadata: {
            /** City */
            city: string;
            /** Code */
            code: string;
            /** Country */
            country: string;
            /** Is Domestic Default */
            is_domestic_default: boolean;
            /** Name */
            name: string;
        };
        /** BankMetadata */
        BankMetadata: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CatalogueFacets */
        CatalogueFacets: {
            /** Banks */
            banks: components["schemas"]["FacetOption"][];
            /** Booking Channels */
            booking_channels: components["schemas"]["FacetOption"][];
            /** Payment Methods */
            payment_methods: components["schemas"]["FacetOption"][];
            /** Platforms */
            platforms: components["schemas"]["FacetOption"][];
        };
        /** FacetOption */
        FacetOption: {
            /** Count */
            count: number;
            /** Disabled */
            disabled: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Selected */
            selected: boolean;
        };
        /** FeatureFlagsResponse */
        FeatureFlagsResponse: {
            /**
             * Alloffers
             * @default true
             */
            allOffers: boolean;
            /**
             * Authenabled
             * @default false
             */
            authEnabled: boolean;
            /** Config Version */
            config_version: string;
            /**
             * Dailyvisitorsenabled
             * @default false
             */
            dailyVisitorsEnabled: boolean;
            /**
             * Offerlockingenabled
             * @default false
             */
            offerLockingEnabled: boolean;
            /**
             * Savedcards
             * @default false
             */
            savedCards: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Offer */
        Offer: {
            /** Bank Id */
            bank_id?: string | null;
            /** Bank Name */
            bank_name?: string | null;
            /**
             * Booking Channel
             * @enum {string}
             */
            booking_channel: "WEB" | "APP" | "WEB_AND_APP";
            /** Booking Url */
            booking_url?: string | null;
            /** Card Name */
            card_name?: string | null;
            /**
             * Category
             * @constant
             */
            category: "FLIGHT_DOMESTIC";
            /** Coupon Code */
            coupon_code?: string | null;
            /**
             * Discount Type
             * @enum {string}
             */
            discount_type: "PERCENT" | "FLAT";
            /** Discount Value */
            discount_value: number;
            /** Eligibility Notes */
            eligibility_notes?: string[];
            /**
             * Evidence Status
             * @enum {string}
             */
            evidence_status: "VERIFIED" | "PARTIAL" | "UNVERIFIED";
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Last Verified At */
            last_verified_at?: string | null;
            /**
             * Login Required
             * @default false
             */
            login_required: boolean;
            /** Max Discount */
            max_discount?: number | null;
            /** Min Transaction */
            min_transaction?: number | null;
            /**
             * New User Only
             * @default false
             */
            new_user_only: boolean;
            /** Offer Id */
            offer_id: string;
            /** Offer Title */
            offer_title: string;
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "CREDIT" | "DEBIT" | "NO_CARD";
            /**
             * Platform Id
             * @enum {string}
             */
            platform_id: "MAKEMYTRIP" | "CLEARTRIP";
            /** Platform Name */
            platform_name: string;
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /**
             * Publish Status
             * @enum {string}
             */
            publish_status: "READY" | "DRAFT" | "HIDDEN";
            /** Source Type */
            source_type?: string | null;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Terms Url */
            terms_url?: string | null;
            /** Usage Limit */
            usage_limit?: string | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
        };
        /** OfferMetadata */
        OfferMetadata: {
            /** Airports */
            airports?: components["schemas"]["AirportMetadata"][];
            /** Banks */
            banks: components["schemas"]["BankMetadata"][];
            /** Booking Channels */
            booking_channels: ("WEB" | "APP" | "WEB_AND_APP")[];
            /** Categories */
            categories: "FLIGHT_DOMESTIC"[];
            /** Data Version */
            data_version: string;
            /** Payment Methods */
            payment_methods: ("CREDIT" | "DEBIT" | "NO_CARD")[];
            /** Platforms */
            platforms: components["schemas"]["PlatformMetadata"][];
        };
        /** OffersResponse */
        OffersResponse: {
            /** Data Version */
            data_version: string;
            facets: components["schemas"]["CatalogueFacets"];
            /** Offers */
            offers: components["schemas"]["Offer"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Pagination */
        Pagination: {
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PlatformMetadata */
        PlatformMetadata: {
            /**
             * Id
             * @enum {string}
             */
            id: "MAKEMYTRIP" | "CLEARTRIP";
            /** Name */
            name: string;
        };
        /** SearchOffer */
        SearchOffer: {
            /** Bank Id */
            bank_id?: string | null;
            /** Bank Name */
            bank_name?: string | null;
            /**
             * Booking Channel
             * @enum {string}
             */
            booking_channel: "WEB" | "APP" | "WEB_AND_APP";
            /** Booking Url */
            booking_url?: string | null;
            /** Card Name */
            card_name?: string | null;
            /**
             * Category
             * @constant
             */
            category: "FLIGHT_DOMESTIC";
            /** Coupon Code */
            coupon_code?: string | null;
            /**
             * Discount Type
             * @enum {string}
             */
            discount_type: "PERCENT" | "FLAT";
            /** Discount Value */
            discount_value: number;
            /** Display Kind */
            display_kind: string;
            /** Display Rank */
            display_rank: number;
            /** Eligibility Notes */
            eligibility_notes?: string[];
            /** Estimated Final Amount */
            estimated_final_amount: number | null;
            /** Estimated Savings */
            estimated_savings: number | null;
            /**
             * Evidence Status
             * @enum {string}
             */
            evidence_status: "VERIFIED" | "PARTIAL" | "UNVERIFIED";
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Last Verified At */
            last_verified_at?: string | null;
            /**
             * Login Required
             * @default false
             */
            login_required: boolean;
            /** Max Discount */
            max_discount?: number | null;
            /** Min Transaction */
            min_transaction?: number | null;
            /**
             * New User Only
             * @default false
             */
            new_user_only: boolean;
            /** Offer Id */
            offer_id: string;
            /** Offer Title */
            offer_title: string;
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "CREDIT" | "DEBIT" | "NO_CARD";
            /**
             * Platform Id
             * @enum {string}
             */
            platform_id: "MAKEMYTRIP" | "CLEARTRIP";
            /** Platform Name */
            platform_name: string;
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /**
             * Publish Status
             * @enum {string}
             */
            publish_status: "READY" | "DRAFT" | "HIDDEN";
            /** Savings Delta */
            savings_delta: number | null;
            /** Savings Label */
            savings_label: string;
            /** Source Type */
            source_type?: string | null;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Terms Url */
            terms_url?: string | null;
            /** Usage Limit */
            usage_limit?: string | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Banks */
            banks?: string[];
            /** Booking Amount */
            booking_amount?: number | string | null;
            /**
             * Category
             * @default FLIGHT_DOMESTIC
             * @constant
             */
            category: "FLIGHT_DOMESTIC";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** From */
            from: string;
            /** Platforms */
            platforms?: ("MAKEMYTRIP" | "CLEARTRIP")[];
            /** To */
            to: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Data Version */
            data_version: string;
            /** Offers */
            offers: components["schemas"]["SearchOffer"][];
            summary: components["schemas"]["SearchSummary"];
        };
        /** SearchSummary */
        SearchSummary: {
            /** Booking Amount */
            booking_amount: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    feature_flags_api_v1_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagsResponse"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferMetadata"];
                };
            };
        };
    };
    offers_api_v1_offers_get: {
        parameters: {
            query?: {
                bank?: string[];
                platform?: string[];
                payment_method?: string[];
                booking_channel?: string[];
                category?: string[];
                active_on?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OffersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
